"""
Interactive Architect Approval Panel.
Displays the winning implementation plan and provides Approve/Reject buttons.
"""

from __future__ import annotations

from textual import on
from textual.app import ComposeResult
from textual.containers import Horizontal, Vertical
from textual.widgets import Button, Input, Label

from src.core.arbiter import ArbiterVerdict
from src.core.logger import get_logger

logger = get_logger("tui.architect_approval_panel")


class ArchitectApprovalPanel(Vertical):
    """
    Renders an approval step for Creator Mode so users can reject or
    modify an Architect's plan before autonomous code tools fire.
    """

    DEFAULT_CSS = """
    ArchitectApprovalPanel {
        width: 100%;
        height: auto;
        border: solid $success;
        background: $background;
        padding: 1 2;
        margin: 1 0;
    }
    .arch-header {
        text-style: bold;
        color: $success;
        margin-bottom: 1;
    }
    .arch-actions {
        height: auto;
        margin-top: 1;
        align-horizontal: right;
    }
    .arch-reject-area {
        display: none;
        margin-top: 1;
        height: auto;
        border: solid $error 50%;
        padding: 1;
    }
    .arch-reject-area.-visible {
        display: block;
    }
    Button {
        margin-left: 1;
    }
    """

    def __init__(self, verdict: ArbiterVerdict, **kwargs) -> None:
        super().__init__(**kwargs)
        self.verdict = verdict

    def compose(self) -> ComposeResult:
        winner = self.verdict.winner
        model_name = winner.model_name if winner else "Agent"
        yield Label("🏗️  Architect Plan Ready", classes="arch-header")
        yield Label(
            f"The Architect ({model_name}) has proposed the implementation plan above. "
            "Please review it before we begin scaffolding code."
        )

        with Horizontal(classes="arch-actions"):
            yield Button("Reject ✕", id="btn-reject", variant="error")
            yield Button("Approve & Build ✓", id="btn-approve", variant="success")

        with Vertical(classes="arch-reject-area", id="reject-area"):
            yield Label("[red]Why are you rejecting this plan?[/red] (optional — helps the AI improve)")
            yield Input(
                placeholder="e.g. Too many files changed, prefer a different approach...",
                id="reject-input",
            )
            yield Button("Send Feedback & Retry", id="btn-reject-confirm", variant="warning")

    @on(Button.Pressed, "#btn-approve")
    def handle_approve(self, event: Button.Pressed) -> None:
        event.stop()
        from src.tui.widgets.toast import notify

        notify(self.app, "Building...", "Executing the architect plan...", "subtle")

        from src.core.events import TaskReceived
        from src.core.mode_manager import OperationMode

        if hasattr(self.app, "orchestrator"):
            self.app.orchestrator.mode_manager.set_mode(OperationMode.STANDARD)

        winning_model = self.verdict.winner.model_name if self.verdict.winner else "the architect"
        build_prompt = f"Please proceed with executing the plan generated by {winning_model}."
        self.app.post_message(TaskReceived(task_str=build_prompt, attached_files=[]))
        self.remove()

    @on(Button.Pressed, "#btn-reject")
    def handle_reject(self, event: Button.Pressed) -> None:
        """Toggle the rejection feedback area instead of immediately dismissing."""
        event.stop()
        ra = self.query_one("#reject-area")
        ra.toggle_class("-visible")
        if "-visible" in ra.classes:
            self.query_one("#reject-input", Input).focus()

    @on(Button.Pressed, "#btn-reject-confirm")
    def handle_reject_confirm(self, event: Button.Pressed) -> None:
        """Send feedback and stay in ARCHITECT mode so next prompt is automatically a new plan."""
        event.stop()
        feedback = self.query_one("#reject-input", Input).value.strip()

        from src.core.events import TaskReceived
        from src.core.mode_manager import OperationMode
        from src.tui.widgets.toast import notify

        if hasattr(self.app, "orchestrator"):
            self.app.orchestrator.mode_manager.set_mode(OperationMode.ARCHITECT)

        if feedback:
            retry_prompt = (
                f"[User rejected the plan] Reason: {feedback}\n\n"
                "Please revise the implementation plan to address this feedback."
            )
        else:
            retry_prompt = "[User rejected the plan] Please revise the implementation plan."

        notify(self.app, "Rejected", "Sending feedback to architect...", "warning")
        self.app.post_message(TaskReceived(task_str=retry_prompt, attached_files=[]))
        self.remove()
