// Phase 6: Part C — Terms of Service
// Created: Phase 6 Polish & Launch Prep

export const metadata = { title: "Terms of Service — gptcgt" };

import Link from "next/link";

export default function TermsOfService() {
    return (
        <>
            <h1>Terms of Service</h1>
            <p><strong>Last updated:</strong> February 2026</p>
            <p><em>This document does not constitute legal advice. By using gptcgt, you agree to these terms.</em></p>

            <h2>1. Service Description</h2>
            <p>gptcgt (&quot;Hydra&quot;) is a terminal-based orchestration platform and IDE that routes user instructions and project code to third-party Large Language Models (LLMs) such as Anthropic, OpenAI, DeepSeek, and Google. We provide intelligent tooling, agent routing, context structuring, and sandboxed verifications; we do not operate the foundational LLMs ourselves.</p>

            <h2>2. Accounts and Eligibility</h2>
            <p>You must be at least 18 years old to use the Service. You are permitted one active account per natural person.</p>

            <h2>3. Subscriptions and Billing</h2>
            <p>Subscriptions renew automatically unless canceled via the Billing Dashboard prior to the end of the term. Managed Credits do not roll over. We reserve the right to modify pricing with 30 days notice. Refunds are available within 14 days of your initial purchase if unsatisfied.</p>

            <h2>4. Acceptable Use Policy</h2>
            <p>By using gptcgt, you must additionally adhere to our <Link href="/legal/aup">Acceptable Use Policy</Link>. We enforce zero tolerance for CSAM (leading to immediate reporting to law enforcement) and strict prohibitions against malicious software creation. Abuse of the AI routing architecture (e.g. jailbreaking or botnet automation) may result in account termination without notice.</p>

            <h2>5. Intellectual Property</h2>
            <p><strong>You retain all ownership rights</strong> to the code, inputs, and project architectures you supply to the Service, as well as the output generated by the AI on your behalf. IA Compa LLC retains all rights to the gptcgt software, including the routing algorithms, TUI interface, arbiter logic, and aggregated anonymized statistics.</p>

            <h2>6. Disclaimers</h2>
            <p>THE SERVICE AND AI OUTPUTS ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;. IA Compa LLC disclaims all warranties, including merchantability or fitness for a particular purpose. Code generated by AI may contain bugs, vulnerabilities, or hallucinations. The built-in Security Scanner and verification sandboxes are provided for informational assistance only and do not replace professional auditing. We are not liable for any code generated through custom third-party or locally hosted providers.</p>

            <h2>7. Limitation of Liability</h2>
            <p>IN NO EVENT SHALL IA COMPA LLC BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR USE. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THIS AGREEMENT SHALL NOT EXCEED THE TOTAL PAID BY YOU FOR THE SERVICE DURING THE TWELVE (12) MONTHS PRIOR TO THE CLAIM, OR $50 IF YOU ARE ON A FREE TIER.</p>

            <h2>8. Dispute Resolution</h2>
            <p>Any dispute arising under these terms shall be subject to binding arbitration governed by the American Arbitration Association in Scioto County, Ohio. You waive any right to participate in a class action lawsuit.</p>

            <h2>9. Termination</h2>
            <p>We may suspend or terminate your access immediately, without notice or liability, if you breach the Acceptable Use Policy. Sections 5 through 8 survive any termination of these Terms.</p>
        </>
    );
}
