export default function TermsPage() {
    return (
        <div className="page-shell py-8">
            <div className="panel-dark mx-auto max-w-4xl px-6 py-10 sm:px-10">
            <div className="mx-auto max-w-3xl text-base leading-7 text-gray-300">
                <p className="text-base font-semibold leading-7 text-indigo-400">gptcgt</p>
                <h1 className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">Terms of Service</h1>
                <p className="mt-6 text-xl leading-8 text-gray-200">
                    Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                </p>
                <div className="mt-10 max-w-2xl text-gray-300">
                    <p>
                        Welcome to gptcgt. By using our terminal application, website, and associated proxy services (collectively, the &quot;Services&quot;), operated by IA Compa LLC, you agree to these Terms of Service.
                    </p>

                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-white">1. Service Description</h2>
                    <p className="mt-6">
                        gptcgt is a Multi-Model AI Coding Terminal that allows developers to interact with various Large Language Models (LLMs) directly from their command line.
                        The service operates via two primary models:
                    </p>
                    <ul className="mt-4 list-disc space-y-2 pl-8">
                        <li><strong>BYOK (Bring Your Own Keys):</strong> You provide your own API keys to third-party services. We provide the software interface.</li>
                        <li><strong>Pro Tier (Managed Credits):</strong> We act as a billing proxy connecting you to various AI providers using our corporate credentials, deducting credits from your account based on token usage.</li>
                    </ul>

                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-white">2. Account Responsibilities</h2>
                    <p className="mt-6">
                        You are responsible for maintaining the confidentiality of your account credentials. You are strictly prohibited from sharing your Pro Tier account, utilizing unauthorized automated scripts to interact with our proxy endpoint, or attempting to reverse-engineer our routing logic.
                    </p>

                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-white">3. Third-Party AI Providers</h2>
                    <p className="mt-6">
                        Our service heavily relies on third-party AI providers (e.g., OpenAI, Anthropic, Google).
                        By using gptcgt, you agree that:
                    </p>
                    <ul className="mt-4 list-disc space-y-2 pl-8">
                        <li>We are not responsible for the accuracy, legality, or quality of the code or text generated by these models.</li>
                        <li>Service availability is contingent upon the uptime of these third-party APIs. Outages at OpenAI or Anthropic may degrade gptcgt&apos;s functionality.</li>
                        <li>You will not use gptcgt to violate the specific Terms of Service of any downstream AI provider we support.</li>
                    </ul>

                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-white">4. Intellectual Property</h2>
                    <p className="mt-6">
                        The gptcgt terminal client, our routing algorithms, and our web dashboard are the intellectual property of IA Compa LLC.
                        <strong>You retain 100% ownership of all code you write and all code generated by the AI models through your use of the Service.</strong>
                    </p>

                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-white">5. Limitation of Liability</h2>
                    <p className="mt-6">
                        gptcgt is a development tool capable of reading and modifying files on your local machine.
                        <strong>You use this tool at your own risk.</strong> IA Compa LLC shall not be liable for any data loss, code corruption, or production downtime resulting from the autonomous actions of AI models executed through our terminal, or from bugs within the gptcgt client itself. Always use version control (e.g., Git) when working with AI tools.
                    </p>

                    <h2 className="mt-16 text-2xl font-bold tracking-tight text-white">6. Termination</h2>
                    <p className="mt-6">
                        We reserve the right to suspend or terminate your access to the Pro Tier or proxy services at any time, with or without cause, specifically in cases of abuse, excessive rate-limiting violations, or non-payment.
                    </p>
                </div>
            </div>
            </div>
        </div>
    );
}
